#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load="$(cut -d ' ' -f1 /proc/loadavg)"
load5="$(cut -d ' ' -f2 /proc/loadavg)"
load15="$(cut -d ' ' -f3 /proc/loadavg)" 
cpus="$(nproc)"

# color if load is too high
if [[ "$(echo "$load < 1 * $cpus" | bc)" = "1" ]]
then
	color="#99CC99"
elif [[ "$(echo "$load < 1.25 * $cpus" | bc)" = "1" ]]
then
	color="#FFCC66"
else
	color="#F2777A"
fi

if [[ "$(echo "$load5 < 1 * $cpus" | bc)" = "1" ]]
then
	color5="#99CC99"
elif [[ "$(echo "$load5 < 1.25 * $cpus" | bc)" = "1" ]]
then
	color5="#FFCC66"
else
	color5="#F2777A"
fi

if [[ "$(echo "$load15 < 1 * $cpus" | bc)" = "1" ]]
then
	color15="#99CC99"
elif [[ "$(echo "$load15 < 1.25 * $cpus" | bc)" = "1" ]]
then
	color15="#FFCC66"
else
	color15="#F2777A"
fi

printf "load <span foreground=\"$color\">%4.4s</span> <span foreground=\"$color5\">%4.4s</span> <span foreground=\"$color15\">%4.4s</span>\n" ${load} ${load5} ${load15}
printf "load <span foreground=\"$color\">%4.4s</span>\n" ${load}
