#!/bin/bash

# Check for an interactive session
[ -z "$PS1" ] && return

# command prompt
export PS1="\[\e[32;1m\]\u@\[\e[32;1m\]\h \[\e[33;1m\]\w/\$ \[\e[0m\]"
# export PS1="\h:\W \u\$"

export EDITOR=vim
export PAGER=less

alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='vim -w PKGBUILD'
#alias more=less


# fix "xdg-open fork-bomb" export your preferred browser from here

alias conf='vim $HOME/.i3/config'
#alias comp='vim $HOME/.config/compton.conf'
alias mk='vim makefile'

alias fixit='sudo rm -f /var/lib/pacman/db.lck'
alias inst='yay -S'
alias update='yay -Syyua'

alias ls='ls --color=auto'
alias la='ls -la --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll='ls -l --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'

alias rm='rm --preserve-root -I -v'

alias mirrors='sudo pacman-mirrors -g'
alias printer='system-config-printer'

alias mv='amv -gi'
alias cp='acp -gir'
alias n='vim'

alias news='newsbeuter'

alias meteo='curl -H "Accept-Language: fr" wttr.in/Châlons-En-Champagne'
alias moon='curl -H "Accept-Language: fr" wttr.in/Moon'

alias backup-user='bash $HOME/dotfiles/scripts/backup/user.sh'

#
# # ex - archive extractor
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
